# Bar, wallpaper
exec-once = ~/.config/hypr/hyprland/scripts/start_geoclue_agent.sh
exec-once = qs -c $qsConfig &
exec-once = ~/.config/hypr/hyprland/scripts/monitor-switch.sh
exec-once = ~/.config/hypr/hyprland/scripts/monitor-daemon.sh

# Input method
# exec-once = fcitx5

# Core components (authentication, lock screen, notification daemon)
# Keyring is now started/unlocked by PAM (authselect with-pam-gnome-keyring)
# exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = hypridle
exec-once = dbus-update-activation-environment --all
exec-once = sleep 1 && dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP # Some fix idk
exec-once = sleep 1 && systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE XDG_SESSION_DESKTOP
# Disabled: can trigger heavy plugin/header rebuilds during login
# exec-once = hyprpm reload

# Audio
exec-once = easyeffects --gapplication-service

# Clipboard: history
# exec-once = wl-paste --watch cliphist store &
exec-once = wl-paste --type text --watch bash -c 'cliphist store && qs -c $qsConfig ipc call cliphistService update'
exec-once = wl-paste --type image --watch bash -c 'cliphist store && qs -c $qsConfig ipc call cliphistService update'

# Cursor (Fedora default)
exec-once = hyprctl setcursor Adwaita 24

# Kitty is now the default terminal

# Enable night light by default
exec-once = ~/.config/hypr/scripts/Hyprsunset.sh init

# Apps to start minimized/tray
